- hosts: server
  gather_facts: true

- hosts: desktop #localhost
  roles:
  - ansible-role-RTMP-Desktop-dev
  - ansible-role-Screen-Resolution
  - ansible-role-Nginx-Restreamer-OBS-Studio-template

  tasks:
  - ansible.builtin.debug:
      msg: "{{ ansible_default_ipv4.address }}"
  

- hosts: server
  vars_files:
    - vars/source.yml
  roles:
  - ansible-role-Nginx
  - ansible-role-Nginx-RTMP-module
  - ansible-role-Nginx-RTMP-template
