- hosts: server
  gather_facts: true

- hosts: desktop #localhost
  roles:
  - UniInc.devEnv-RTMP-Desktop
  - UniInc.Screen-Resolution
  - UniInc.template-Nginx-Restreamer-OBS-Studio

  tasks:
  - ansible.builtin.debug:
      msg: "{{ ansible_default_ipv4.address }}"
  

- hosts: server
  vars_files:
    - vars/source.yml
  roles:
  - UniInc.Nginx
  - UniInc.Nginx-RTMP-module
  - UniInc.template-Nginx-RTMP
